### PR TITLE
Copy Item & Delete Multiple

### PR DESCRIPTION
**Pull request by Snivik**
I needed a way to copy-paste events since they're 90% matching the content, so I created an ability to copy-paste an entity. I also added checkboxes to each row which should let you select multiple things to perform actions. So far I added only "delete".

**Thing to-do that I think should be done before merging to main**

- [ ] Add confirmation before delete
- [ ] Fix sizing issues of a new "first column". Basically it's barely usable on sizes less than "M"

### CODE REVIEW

**Comment by fgatti675** [comment]
Hi @Snivik, thanks for the PR! 
It's a couple of nice features. As you say, I'd think of how to handle the smaller configuration of the table, maybe reducing all the icon sizes and margins.
I'd also add the confirmation dialog before batch deletion, and maybe change the color of the button so it does not feel like a CTA.
What I would also do, is: when clicking on the copy button, instead of simply creating a new entity with an automatically generated id, I would open the new entity side dialog, so the user can jump into modifying the new entity, assign an id (if the schema is configured as such) and discard in case he pressed by mistake.
If the table has enough entries, the newly created (copied) entity could be in a different page and not be displayed.
Great job!

**Comment by Snivik** [comment]
Glad to help,

Are there any tips on how to reuse your create form and pre-fill it with an existing Entity? I was thinking about going that route initially, but since I needed a quick solution for the project, I went with copy-pasting the JSON directly to the fb.

Changing color and confirmation should be quite easy.

Thanks!

**Comment by fgatti675** [comment]
@Snivik I have handpicked your changes and adapted them. They are now merged in the master branch and released in version 0.23.0
Thanks a lot for your effort!

**Comment by Snivik** [comment]
Apologies for not addressing this stuff myself. I'm using FireCMS for a personal project and I've been working through the weekends for the past month, didn't have time to even do the simple stuff like color change for the buttons. Once I get a chance I'll try to advance the update feature and create another pull if needed!

Thanks a lot!

**Pull request closed without merging**
