### PR TITLE
Add image compression and resizing to StorageUploadField

### PR DESCRIPTION
**Pull request by doxsch**
On the `StorageUploadField` you can new optional define if the images should be scaled and compressed before the upload. This is only valid for png, jpeg and webp files. 
For scaling and compressing `react-image-file-resizer` is used.

### CODE REVIEW

**Comment by fgatti675** [comment]
Hi man, thanks for the PR, could you rebase it into `master` though?
The `pre` branch is really outdated.
Thanks!

**Comment by doxsch** [comment]
Have now adjusted the branch so that it fits on the `master`.

I originally set it to `pre` so it would be compatible with v1. Would find it helpful if we could backport this feature.

**Comment by fgatti675** [comment]
I have manually merged this PR and release it in `2.0.0-alpha.38`
Thanks a lot for the feature!!
If you would like to have it in v1, you can submit a nnew PR to the `v1` branch

**Comment by doxsch** [comment]
> I have manually merged this PR and release it in `2.0.0-alpha.38` Thanks a lot for the feature!! If you would like to have it in v1, you can submit a nnew PR to the `v1` branch

Thanks for merging. As you suggested, I opened an MR for the v1 backport: https://github.com/Camberi/firecms/pull/407

**Pull request closed without merging**
